/**
 * authored-wording.ts — GENERATED from docs/rules/*.md AUTHORED blocks
 * by scripts/generate-wording-seed.mjs.
 *
 * Do NOT hand-edit. Re-run `node scripts/generate-wording-seed.mjs`
 * after any change to docs/rules/*.md AUTHORED blocks.
 */
export const AUTHORED_WORDING = [
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "efficiency_at_cost_of_volume",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend fell {{spend_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}. Outcome held up better than spend did, by {{axis_spread_pct}}.|That is efficiency at the cost of volume rather than a broken pullback.|Spend bought more {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "efficiency_at_cost_of_volume",
        locale: "en-AU",
        model: "lead_generation",
        template: "Efficiency at cost of volume",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "proportional_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend fell {{spend_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}.|Both moved together and efficiency did not shift materially.|Decline came on less spend, not on getting less per {{currency_unit_singular}}.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "proportional_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "Proportional pullback",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "broken_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend fell {{spend_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}. Outcome fell faster than spend, by {{axis_spread_pct}}.|That is a broken pullback rather than efficiency held through a lower spend.|Spend bought {{fewer_or_less}} {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "broken_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "Broken pullback",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "spend_cut_absorbed",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend fell {{spend_delta_pct}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Efficiency rose by {{efficiency_delta_pct}}.|That is outcome held on less spend rather than growth on less spend.|Spend bought more {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "spend_cut_absorbed",
        locale: "en-AU",
        model: "lead_generation",
        template: "Outcome held on less spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "efficiency_gain_on_cut",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend fell {{spend_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}. Efficiency rose by {{efficiency_delta_pct}}.|That is growth on less spend rather than outcome held on less spend.|Spend bought more {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "efficiency_gain_on_cut",
        locale: "en-AU",
        model: "lead_generation",
        template: "Growth on less spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "less_at_held_spend",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. The account produced less on {{spend_band_phrase}} budget. Efficiency fell by {{efficiency_delta_pct}}.|That is less at held spend rather than a proportional pullback, and it is the more concerning of the two.|The drop is not explained by a material spend change, so whatever caused it is still in place.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "less_at_held_spend",
        locale: "en-AU",
        model: "lead_generation",
        template: "Less at held spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "stable",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend and {{primary_outcome_noun}} both held. That is a stable month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "stable",
        locale: "en-AU",
        model: "lead_generation",
        template: "Stable",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "more_at_held_spend__tier_1plus",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. The account produced more on {{spend_band_phrase}} budget.|That is more at held spend rather than growth, and it is the more durable of the two.|The improvement holds at the current spend level and does not depend on continued investment to sustain it.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "more_at_held_spend",
        locale: "en-AU",
        model: "lead_generation",
        template: "More at held spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "more_at_held_spend__tier_0",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. The account produced more on {{spend_band_phrase}} budget.|That is more at held spend rather than growth, and it is the more durable of the two.|The improvement holds at the current spend level.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "wasted_scaling",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend rose {{spend_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}. Efficiency fell by {{efficiency_delta_pct}}.|That is decline on more spend rather than outcome held on more spend.|Spend bought {{fewer_or_less}} {{primary_outcome_noun}} per {{currency_unit_singular}} than last month, and total {{primary_outcome_noun}} dropped as well.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "wasted_scaling",
        locale: "en-AU",
        model: "lead_generation",
        template: "Decline on more spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "scaling_without_lift",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend rose {{spend_delta_pct}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Efficiency fell by {{efficiency_delta_pct}}.|That is outcome held on more spend rather than decline on more spend.|Spend bought {{fewer_or_less}} {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "scaling_without_lift",
        locale: "en-AU",
        model: "lead_generation",
        template: "Outcome held on more spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "strong_month",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend rose {{spend_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}. Outcome outran spend by {{axis_spread_pct}}.|That is a strong month rather than volume alone.|Spend bought more {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "strong_month",
        locale: "en-AU",
        model: "lead_generation",
        template: "Growth outran spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "breakthrough",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend rose {{spend_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}. Outcome outran spend by {{axis_spread_pct}}.|That is a breakthrough month rather than a strong one.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "breakthrough",
        locale: "en-AU",
        model: "lead_generation",
        template: "Breakthrough",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "volume_bought",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend rose {{spend_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}.|Both moved together and efficiency did not shift materially.|Growth came on more spend, not on getting more per {{currency_unit_singular}}.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "volume_bought",
        locale: "en-AU",
        model: "lead_generation",
        template: "Growth on more spend",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "diminishing_returns",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend rose faster than results. The account bought growth and paid more for each unit of it.|That is diminishing returns rather than a broken account.|Spend bought {{fewer_or_less}} {{primary_outcome_noun}} per {{currency_unit_singular}} than last month, though total {{primary_outcome_noun}} still grew.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "diminishing_returns",
        locale: "en-AU",
        model: "lead_generation",
        template: "Diminishing returns",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "silent_efficiency_gain",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend {{spend_move_phrase}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Efficiency rose by {{efficiency_delta_pct}}.|That is a silent efficiency gain rather than a stable month.|Spend bought more {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "silent_efficiency_gain",
        locale: "en-AU",
        model: "lead_generation",
        template: "Silent efficiency gain",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthComposition",
        branch_key: "silent_efficiency_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Spend {{spend_move_phrase}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Efficiency fell by {{efficiency_delta_pct}}.|That is a silent efficiency loss rather than a stable month.|Spend bought {{fewer_or_less}} {{primary_outcome_noun}} per {{currency_unit_singular}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthComposition",
        branch_key: "silent_efficiency_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "Silent efficiency loss",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "resilient_decline",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions fell {{sessions_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}. {{primary_outcome_noun}} held up better than sessions did, by {{axis_spread_pct}}.|That is a resilient decline rather than a broken pullback.|The average session produced more {{primary_outcome_noun}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "resilient_decline",
        locale: "en-AU",
        model: "lead_generation",
        template: "Resilient decline",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "web_proportional_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions fell {{sessions_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}.|Both moved together and conversion rate did not shift materially.|Decline came on fewer sessions, not on getting {{fewer_or_less}} per session.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "web_proportional_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "Proportional pullback",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "web_broken_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions fell {{sessions_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}. {{primary_outcome_noun}} fell faster than sessions, by {{axis_spread_pct}}.|That is a broken pullback rather than a resilient decline.|The average session produced {{fewer_or_less}} {{primary_outcome_noun}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "web_broken_pullback",
        locale: "en-AU",
        model: "lead_generation",
        template: "Broken pullback",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "rate_lift_on_traffic_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions fell {{sessions_delta_pct}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Conversion rate rose by {{efficiency_delta_pct}}.|That is a rate lift on traffic loss rather than efficiency gain on traffic loss.|The rate rose because fewer sessions came in, not because each session converted more.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "rate_lift_on_traffic_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "Rate lift on traffic loss",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "efficiency_gain_on_traffic_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions fell {{sessions_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}. Conversion rate rose by {{efficiency_delta_pct}}.|That is efficiency gain on traffic loss rather than a rate lift on lost traffic.|The average session produced more {{primary_outcome_noun}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "efficiency_gain_on_traffic_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "Efficiency gain on traffic loss",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "less_at_held_traffic",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. The site produced less on {{sessions_band_phrase}} traffic. Conversion rate fell by {{efficiency_delta_pct}}.|That is less at held traffic rather than a pullback, and it is the more concerning of the two.|The drop is not explained by a material traffic change, so whatever caused it is still in place.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "less_at_held_traffic",
        locale: "en-AU",
        model: "lead_generation",
        template: "Less at held traffic",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "stable",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions and {{primary_outcome_noun}} both held. That is a stable month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "stable",
        locale: "en-AU",
        model: "lead_generation",
        template: "Stable",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "more_at_held_traffic",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. The site produced more on {{sessions_band_phrase}} traffic.|That is more at held traffic rather than growth, and it is the more durable of the two.|The improvement holds at the current traffic level.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "more_at_held_traffic",
        locale: "en-AU",
        model: "lead_generation",
        template: "More at held traffic",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "growth_without_conversion",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions rose {{sessions_delta_pct}} and {{primary_outcome_noun}} fell {{outcome_delta_pct}}. Conversion rate fell by {{efficiency_delta_pct}}.|That is growth without conversion rather than a strong month.|The average session produced fewer {{primary_outcome_noun}} than last month, and total {{primary_outcome_noun}} fell as well.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "growth_without_conversion",
        locale: "en-AU",
        model: "lead_generation",
        template: "Growth without conversion",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "flag:describeGrowthCompositionWeb:growth_without_conversion",
        branch_key: "growth_without_conversion",
        locale: "en-AU",
        model: "lead_generation",
        template: "Flag. Sessions rose {{sessions_delta_pct}} while {{primary_outcome_noun}} fell {{outcome_delta_pct}}. Whether that is a conversion issue, a tracking fault, or a mix shift in traffic quality cannot be settled from the deltas alone. Check the per-source and per-page detail before concluding.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "diluted_growth",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions rose {{sessions_delta_pct}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Conversion rate fell by {{efficiency_delta_pct}}.|That is diluted growth rather than an efficiency loss.|The rate fell because more sessions came in, not because each session converted less.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "diluted_growth",
        locale: "en-AU",
        model: "lead_generation",
        template: "Diluted growth",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "strong",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions rose {{sessions_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}. {{primary_outcome_noun}} outran sessions by {{axis_spread_pct}}.|That is a strong month rather than traffic alone.|The average session produced more {{primary_outcome_noun}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "strong",
        locale: "en-AU",
        model: "lead_generation",
        template: "Growth outran traffic",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "traffic_led_growth",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions rose {{sessions_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}.|Both moved together and conversion rate did not shift materially.|Growth came on more traffic, not on getting more per session.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "traffic_led_growth",
        locale: "en-AU",
        model: "lead_generation",
        template: "Traffic-led growth",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "diminishing_returns",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions rose {{sessions_delta_pct}} and {{primary_outcome_noun}} rose {{outcome_delta_pct}}. Sessions outran {{primary_outcome_noun}} by {{axis_spread_pct}}.|That is diminishing returns rather than a broken site.|The average session produced {{fewer_or_less}} {{primary_outcome_noun}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "diminishing_returns",
        locale: "en-AU",
        model: "lead_generation",
        template: "Diminishing returns",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "silent_efficiency_gain",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions {{sessions_move_phrase}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Conversion rate rose by {{efficiency_delta_pct}}.|That is a silent efficiency gain rather than a stable month.|The average session produced more {{primary_outcome_noun}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "silent_efficiency_gain",
        locale: "en-AU",
        model: "lead_generation",
        template: "Silent efficiency gain",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "silent_efficiency_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "The shape of the month. Sessions {{sessions_move_phrase}} and {{primary_outcome_noun}} {{outcome_band_phrase}}. Conversion rate fell by {{efficiency_delta_pct}}.|That is a silent efficiency loss rather than a stable month.|The average session produced {{fewer_or_less}} {{primary_outcome_noun}} than last month.",
        provisional: false,
    },
    {
        key_type: "chip_label",
        rule_id: "describeGrowthCompositionWeb",
        branch_key: "silent_efficiency_loss",
        locale: "en-AU",
        model: "lead_generation",
        template: "Silent efficiency loss",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeAnchor",
        branch_key: "_default",
        locale: "en-AU",
        model: "lead_generation",
        template: "The month. {{spend_current}} spent, {{spend_direction}} {{spend_delta_pct}} on {{prior_month_short}}, producing {{outcome_current}} {{primary_outcome_noun}} at a {{cpa_current}} cost per acquisition.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeAnchorDeltas",
        branch_key: "_default",
        locale: "en-AU",
        model: "lead_generation",
        template: "{{primary_outcome_noun_capitalized}} {{outcome_direction}} {{outcome_delta_pct}} and CPA {{cpa_direction}} {{cpa_delta_pct}}.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeOutcomeDefinition",
        branch_key: "_default",
        locale: "en-AU",
        model: "lead_generation",
        template: "{{primary_outcome_noun_capitalized}} are {{conversion_definition}}.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeAnchorWeb",
        branch_key: "_default",
        locale: "en-AU",
        model: "lead_generation",
        template: "The month. {{sessions_current}} sessions from {{users_current}} users, producing {{lead_events_current}} lead events at a {{conversion_rate_current_pct}} conversion rate, across {{page_views_current}} page views.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeAnchorDeltasWeb",
        branch_key: "_default",
        locale: "en-AU",
        model: "lead_generation",
        template: "Against {{prior_month_short}}: sessions {{sessions_direction}} {{sessions_delta_pct}}, users {{users_direction}} {{users_delta_pct}}, lead events {{leads_direction}} {{leads_delta_pct}}, conversion rate {{conversion_rate_direction}} from {{conversion_rate_prior_pct}}.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describePagesPerSession",
        branch_key: "_default",
        locale: "en-AU",
        model: "lead_generation",
        template: "Pages per session {{pages_per_session_direction}} from {{pages_per_session_prior}} to {{pages_per_session_current}}.",
        provisional: false,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeOutcomeDecomposition",
        branch_key: "bought_and_launched",
        locale: "en-AU",
        model: "lead_generation",
        template: "What drove it. {{dominant_driver_phrase_capitalised}} was the dominant driver of the {{total_delta_magnitude}} additional {{outcome_noun_countable}}, contributing {{dominant_contribution_magnitude}}{{secondary_clause}}{{counteracting_clause}}.{{lifecycle_clause}}|That is bought and launched.|Growth on this pattern continues only while the spend does.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeOutcomeDecomposition",
        branch_key: "earned_growth",
        locale: "en-AU",
        model: "lead_generation",
        template: "What drove it. {{dominant_driver_phrase_capitalised}} was the dominant driver of the {{total_delta_magnitude}} additional {{outcome_noun_countable}}, contributing {{dominant_contribution_magnitude}}{{secondary_clause}}{{counteracting_clause}}.{{lifecycle_clause}}|That is earned growth.|The improvement does not depend on spending more.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeOutcomeDecomposition",
        branch_key: "default",
        locale: "en-AU",
        model: "lead_generation",
        template: "What drove it. {{dominant_driver_phrase_capitalised}} was the dominant driver of the {{total_delta_magnitude}} {{delta_word}} {{outcome_noun_countable}}, contributing {{dominant_contribution_magnitude}}{{secondary_clause}}{{counteracting_clause}}.{{lifecycle_clause}}|That is the shape of the month's {{outcome_shape_word}}.|Watch this driver as the main lever.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeOutcomeDecompositionWeb",
        branch_key: "traffic_driven",
        locale: "en-AU",
        model: "lead_generation",
        template: "What drove it. {{dominant_driver_phrase_capitalised}} were the dominant driver of the {{total_delta_magnitude}} additional {{outcome_noun_countable}}, contributing {{dominant_contribution_magnitude}}{{secondary_clause}}{{counteracting_clause}}.{{lifecycle_clause}}|That is traffic-driven.|The growth is on the traffic axis alone; a change in per-visit conversion would change the pattern.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeOutcomeDecompositionWeb",
        branch_key: "earned_growth",
        locale: "en-AU",
        model: "lead_generation",
        template: "What drove it. {{dominant_driver_phrase_capitalised}} was the dominant driver of the {{total_delta_magnitude}} additional {{outcome_noun_countable}}, contributing {{dominant_contribution_magnitude}}{{secondary_clause}}{{counteracting_clause}}.{{lifecycle_clause}}|That is earned growth.|The improvement does not depend on more sessions.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeOutcomeDecompositionWeb",
        branch_key: "default",
        locale: "en-AU",
        model: "lead_generation",
        template: "What drove it. {{dominant_driver_phrase_capitalised}} was the dominant driver of the {{total_delta_magnitude}} {{delta_word}} {{outcome_noun_countable}}, contributing {{dominant_contribution_magnitude}}{{secondary_clause}}{{counteracting_clause}}.{{lifecycle_clause}}|That is the shape of the month's {{outcome_shape_word}}.|Watch this driver as the main lever.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeSpendDecomposition",
        branch_key: "_default",
        locale: "en-AU",
        model: "lead_generation",
        template: "Campaign performance. {{best_performer_clause}}{{took_most_of_increase_clause}}{{new_entrant_clause}}{{stopped_clause}}",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeStatisticallySignificantRateChange",
        branch_key: "ctr_only",
        locale: "en-AU",
        model: "lead_generation",
        template: "Statistical significance. CTR moved from {{ctr_prior_pct}} to {{ctr_current_pct}}, a statistically significant change against the {{prior_month_short}} sample.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeStatisticallySignificantRateChange",
        branch_key: "cr_only",
        locale: "en-AU",
        model: "lead_generation",
        template: "Statistical significance. Conversion rate moved from {{cr_prior_pct}} to {{cr_current_pct}}, a statistically significant change against the {{prior_month_short}} sample.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeStatisticallySignificantRateChange",
        branch_key: "both",
        locale: "en-AU",
        model: "lead_generation",
        template: "Statistical significance. CTR moved from {{ctr_prior_pct}} to {{ctr_current_pct}} and conversion rate moved from {{cr_prior_pct}} to {{cr_current_pct}}, both statistically significant against the {{prior_month_short}} sample.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_efficiency_at_cost_of_volume",
        locale: "en-AU",
        model: "any",
        template: "The month pulled back on {{prior_month_short}}; efficiency improved as volume fell less than spend.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_proportional_pullback",
        locale: "en-AU",
        model: "any",
        template: "The month scaled down from {{prior_month_short}}; conversions and spend fell in step, no efficiency change.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_broken_pullback",
        locale: "en-AU",
        model: "any",
        template: "The month's cut on {{prior_month_short}} broke something; conversions fell faster than budget and costs rose.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_spend_cut_absorbed",
        locale: "en-AU",
        model: "any",
        template: "Spend fell on {{prior_month_short}} and output held; each dollar bought more than it did last month.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_efficiency_gain_on_cut",
        locale: "en-AU",
        model: "any",
        template: "The month improved on {{prior_month_short}} with less spend; the account is performing better at a lower cost base.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_less_at_held_spend",
        locale: "en-AU",
        model: "any",
        template: "The month softened on {{prior_month_short}} at the same budget; the same spend produced fewer conversions.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_stable",
        locale: "en-AU",
        model: "any",
        template: "A stable month compared with {{prior_month_short}}; nothing moved materially.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_more_at_held_spend",
        locale: "en-AU",
        model: "any",
        template: "The month improved on {{prior_month_short}} at the same budget; the improvement does not depend on spending more.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_wasted_scaling",
        locale: "en-AU",
        model: "any",
        template: "The month spent more than {{prior_month_short}} without result; something in the funnel is not scaling.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_scaling_without_lift",
        locale: "en-AU",
        model: "any",
        template: "Spend rose on {{prior_month_short}} without a matching lift in output; more spend did not translate to more output.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_strong_month",
        locale: "en-AU",
        model: "any",
        template: "The month improved on {{prior_month_short}}: budget and efficiency both moved in the right direction.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_breakthrough",
        locale: "en-AU",
        model: "any",
        template: "The month broke through on {{prior_month_short}}: less budget produced more, and cost per acquisition fell.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_volume_bought",
        locale: "en-AU",
        model: "any",
        template: "The month grew on {{prior_month_short}} through budget, not efficiency; conversion rate held steady.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_diminishing_returns",
        locale: "en-AU",
        model: "any",
        template: "The month grew on {{prior_month_short}} but at lower efficiency; additional spend produced less per dollar.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_silent_efficiency_gain",
        locale: "en-AU",
        model: "any",
        template: "A quiet improvement on {{prior_month_short}}: budget and conversions did not move materially, but each dollar bought more than it did last month.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_silent_efficiency_loss",
        locale: "en-AU",
        model: "any",
        template: "A quiet softening on {{prior_month_short}}: budget and conversions did not move materially, but each dollar bought less than it did last month.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b1_insufficient_data",
        locale: "en-AU",
        model: "any",
        template: "Insufficient data to assess movement against {{prior_month_short}}.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_resilient_decline",
        locale: "en-AU",
        model: "any",
        template: "The month declined on {{prior_month_short}} but lead events fell less than sessions; conversion rate rose as sessions fell.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_web_proportional_pullback",
        locale: "en-AU",
        model: "any",
        template: "The website scaled down from {{prior_month_short}}; sessions and lead events fell in step.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_web_broken_pullback",
        locale: "en-AU",
        model: "any",
        template: "The website softened on {{prior_month_short}}: both traffic and lead events fell.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_rate_lift_on_traffic_loss",
        locale: "en-AU",
        model: "any",
        template: "Sessions fell on {{prior_month_short}} while lead events held; the rise in conversion rate reflects fewer sessions, not stronger conversion.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_efficiency_gain_on_traffic_loss",
        locale: "en-AU",
        model: "any",
        template: "Sessions fell on {{prior_month_short}} but lead events rose; the rise in conversion rate is real, not just a rate lift on lost traffic.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_less_at_held_traffic",
        locale: "en-AU",
        model: "any",
        template: "The month softened on {{prior_month_short}} at the same traffic; the same sessions produced fewer lead events.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_stable",
        locale: "en-AU",
        model: "any",
        template: "A stable month for the website compared with {{prior_month_short}}; nothing moved materially.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_more_at_held_traffic",
        locale: "en-AU",
        model: "any",
        template: "Sessions held on {{prior_month_short}} and lead events rose; the improvement does not depend on more traffic.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_growth_without_conversion",
        locale: "en-AU",
        model: "any",
        template: "The month softened on {{prior_month_short}} though sessions rose; the sessions rise does not offset the fall in lead events.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_diluted_growth",
        locale: "en-AU",
        model: "any",
        template: "Sessions rose on {{prior_month_short}} and lead events held; the fall in conversion rate is a volume effect, not a conversion problem.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_strong",
        locale: "en-AU",
        model: "any",
        template: "The website improved on {{prior_month_short}}: sessions and lead events both grew, and conversion rate lifted.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_traffic_led_growth",
        locale: "en-AU",
        model: "any",
        template: "The website grew on {{prior_month_short}} through traffic, not conversion; more visits at a stable rate.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_diminishing_returns",
        locale: "en-AU",
        model: "any",
        template: "The website grew traffic on {{prior_month_short}} but lead events grew less; conversion rate softened.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_silent_efficiency_gain",
        locale: "en-AU",
        model: "any",
        template: "A quiet improvement on {{prior_month_short}}: traffic and lead events did not move materially, but each session produced more lead events than last month.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_silent_efficiency_loss",
        locale: "en-AU",
        model: "any",
        template: "A quiet softening on {{prior_month_short}}: traffic and lead events did not move materially, but each session produced fewer lead events than last month.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "b2_insufficient_data",
        locale: "en-AU",
        model: "any",
        template: "Insufficient data to assess website movement against {{prior_month_short}}.",
        provisional: true,
    },
    {
        key_type: "finding_signal",
        rule_id: "describeVerdict",
        branch_key: "no_composition_data",
        locale: "en-AU",
        model: "any",
        template: "An assessment against {{prior_month_short}} could not be composed; upstream composition finding is unavailable.",
        provisional: true,
    },
];
//# sourceMappingURL=authored-wording.js.map