// Server-only. Holds ATWORK_CONFIG (imports @prism/executive-summaries which
// pulls node:crypto through the engine's data-hash module). Kept out of
// adapters/config.ts so the client-side page.tsx bundle doesn't pick up
// PRISM as a transitive import.
//
// Static fallback ClientConfig used until reporting.client / reporting.config
// are seeded for slug 'atwork'. Once seeded, swap for a loader call.

import 'server-only';
import type { ClientConfig, WordingOverride } from '@prism/executive-summaries';
import { DEFAULT_THRESHOLDS } from '@prism/executive-summaries';
// Wording templates authored inside PRISM's docs/rules/*.md — generated by
// `npm run seed:wording` in the PRISM repo, copied here (114 rows) so
// composed reports render authored prose instead of PLACEHOLDER strings.
// Regenerate + re-copy after PRISM authoring changes.
import { AUTHORED_WORDING } from '@/lib/authored-wording.js';

export const ATWORK_CONFIG: ClientConfig = {
  client_slug:           'atwork',
  version:               1,
  config_id:             null,
  currency:              'AUD',
  locale:                'en-AU',
  default_outcome_model: 'lead_generation',
  thresholds:            DEFAULT_THRESHOLDS,
  channels:              [],
  rules:                 [],
  tone:                  { tone: 'advisory', show_implication: true, show_action_only: false },
  layout: {
    tier_order:             ['tl_dr', 'scorecard', 'trends', 'waterfall', 'narrative', 'recommendations', 'evidence'],
    render_flags:           true,
    render_recommendations: true,
    render_waterfall:       true,
    render_evidence:        true,
  },
  wording: AUTHORED_WORDING as WordingOverride[],
};
